"""add_customer_name

Revision ID: 15958875c599
Revises: 
Create Date: 2025-02-13 15:18:00.716558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15958875c599'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bang_keo_in_orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('thoi_gian', sa.DateTime(), nullable=True),
    sa.Column('ten_hang', sa.String(length=255), nullable=False),
    sa.Column('ten_khach_hang', sa.String(length=255), nullable=False),
    sa.Column('ngay_du_kien', sa.Date(), nullable=False),
    sa.Column('quy_cach_mm', sa.Float(), nullable=True),
    sa.Column('quy_cach_m', sa.Float(), nullable=True),
    sa.Column('quy_cach_mic', sa.Float(), nullable=True),
    sa.Column('cuon_cay', sa.Float(), nullable=True),
    sa.Column('so_luong', sa.Float(), nullable=False),
    sa.Column('phi_sl', sa.Float(), nullable=True),
    sa.Column('mau_keo', sa.String(length=100), nullable=True),
    sa.Column('phi_keo', sa.Float(), nullable=True),
    sa.Column('mau_sac', sa.String(length=100), nullable=True),
    sa.Column('phi_mau', sa.Float(), nullable=True),
    sa.Column('phi_size', sa.Float(), nullable=True),
    sa.Column('phi_cat', sa.Float(), nullable=True),
    sa.Column('don_gia_von', sa.Float(), nullable=True),
    sa.Column('don_gia_goc', sa.Float(), nullable=True),
    sa.Column('thanh_tien_goc', sa.Float(), nullable=True),
    sa.Column('don_gia_ban', sa.Float(), nullable=False),
    sa.Column('thanh_tien_ban', sa.Float(), nullable=True),
    sa.Column('tien_coc', sa.Float(), nullable=True),
    sa.Column('cong_no_khach', sa.Float(), nullable=True),
    sa.Column('ctv', sa.String(length=100), nullable=True),
    sa.Column('hoa_hong', sa.Float(), nullable=True),
    sa.Column('tien_hoa_hong', sa.Float(), nullable=True),
    sa.Column('loi_giay', sa.String(length=100), nullable=True),
    sa.Column('thung_bao', sa.String(length=100), nullable=True),
    sa.Column('loi_nhuan', sa.Float(), nullable=True),
    sa.Column('tien_ship', sa.Float(), nullable=True),
    sa.Column('loi_nhuan_rong', sa.Float(), nullable=True),
    sa.Column('da_giao', sa.Boolean(), nullable=True),
    sa.Column('da_tat_toan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bang_keo_orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('thoi_gian', sa.DateTime(), nullable=True),
    sa.Column('ten_hang', sa.String(length=255), nullable=False),
    sa.Column('ten_khach_hang', sa.String(length=255), nullable=False),
    sa.Column('ngay_du_kien', sa.Date(), nullable=False),
    sa.Column('quy_cach', sa.String(length=100), nullable=True),
    sa.Column('so_luong', sa.Float(), nullable=False),
    sa.Column('mau_sac', sa.String(length=100), nullable=True),
    sa.Column('don_gia_goc', sa.Float(), nullable=True),
    sa.Column('thanh_tien', sa.Float(), nullable=True),
    sa.Column('don_gia_ban', sa.Float(), nullable=False),
    sa.Column('thanh_tien_ban', sa.Float(), nullable=True),
    sa.Column('cong_no_khach', sa.Float(), nullable=True),
    sa.Column('ctv', sa.String(length=100), nullable=True),
    sa.Column('hoa_hong', sa.Float(), nullable=True),
    sa.Column('tien_hoa_hong', sa.Float(), nullable=True),
    sa.Column('loi_nhuan', sa.Float(), nullable=True),
    sa.Column('tien_ship', sa.Float(), nullable=True),
    sa.Column('loi_nhuan_rong', sa.Float(), nullable=True),
    sa.Column('da_giao', sa.Boolean(), nullable=True),
    sa.Column('da_tat_toan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngay_dat', sa.DateTime(), nullable=True),
    sa.Column('ngay_du_kien', sa.DateTime(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('da_giao', sa.Boolean(), nullable=True),
    sa.Column('da_tat_toan', sa.Boolean(), nullable=True),
    sa.Column('ghi_chu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('truc_in_orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('thoi_gian', sa.DateTime(), nullable=True),
    sa.Column('ten_hang', sa.String(length=255), nullable=False),
    sa.Column('ten_khach_hang', sa.String(length=255), nullable=False),
    sa.Column('ngay_du_kien', sa.Date(), nullable=False),
    sa.Column('quy_cach', sa.String(length=100), nullable=True),
    sa.Column('so_luong', sa.Float(), nullable=False),
    sa.Column('mau_sac', sa.String(length=100), nullable=True),
    sa.Column('mau_keo', sa.String(length=100), nullable=True),
    sa.Column('don_gia_goc', sa.Float(), nullable=True),
    sa.Column('thanh_tien_goc', sa.Float(), nullable=True),
    sa.Column('don_gia_ban', sa.Float(), nullable=False),
    sa.Column('thanh_tien_ban', sa.Float(), nullable=True),
    sa.Column('cong_no_khach', sa.Float(), nullable=True),
    sa.Column('ctv', sa.String(length=100), nullable=True),
    sa.Column('hoa_hong', sa.Float(), nullable=True),
    sa.Column('tien_hoa_hong', sa.Float(), nullable=True),
    sa.Column('loi_nhuan', sa.Float(), nullable=True),
    sa.Column('tien_ship', sa.Float(), nullable=True),
    sa.Column('loi_nhuan_rong', sa.Float(), nullable=True),
    sa.Column('da_giao', sa.Boolean(), nullable=True),
    sa.Column('da_tat_toan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=True),
    sa.Column('ten_hang', sa.String(), nullable=True),
    sa.Column('so_luong', sa.Integer(), nullable=True),
    sa.Column('don_gia', sa.Float(), nullable=True),
    sa.Column('thanh_tien', sa.Float(), nullable=True),
    sa.Column('quy_cach', sa.String(), nullable=True),
    sa.Column('mau_sac', sa.String(), nullable=True),
    sa.Column('mau_keo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chi_tiet_don_hang')
    op.drop_table('truc_in_orders')
    op.drop_table('don_hang')
    op.drop_table('bang_keo_orders')
    op.drop_table('bang_keo_in_orders')
    # ### end Alembic commands ###
