"""rename thanh_tien to thanh_tien_goc in truc_in_orders

Revision ID: d6925d93b335
Revises: 15958875c599
Create Date: 2025-02-13 16:31:19.006586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6925d93b335'
down_revision: Union[str, None] = '15958875c599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('don_hang')
    op.drop_table('chi_tiet_don_hang')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('don_hang_id', sa.INTEGER(), nullable=True),
    sa.Column('ten_hang', sa.VARCHAR(), nullable=True),
    sa.Column('so_luong', sa.INTEGER(), nullable=True),
    sa.Column('don_gia', sa.FLOAT(), nullable=True),
    sa.Column('thanh_tien', sa.FLOAT(), nullable=True),
    sa.Column('quy_cach', sa.VARCHAR(), nullable=True),
    sa.Column('mau_sac', sa.VARCHAR(), nullable=True),
    sa.Column('mau_keo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('don_hang',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ngay_dat', sa.DATETIME(), nullable=True),
    sa.Column('ngay_du_kien', sa.DATETIME(), nullable=True),
    sa.Column('trang_thai', sa.VARCHAR(), nullable=True),
    sa.Column('da_giao', sa.BOOLEAN(), nullable=True),
    sa.Column('da_tat_toan', sa.BOOLEAN(), nullable=True),
    sa.Column('ghi_chu', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
